application:
    app: RAIZ
    booleano: RAIZ
    carplate: RAIZ
    description: RAIZ
    environment: RAIZ
    force: RAIZ
    goal: RAIZ

configuration:
    test: active
    test-message: esta é uma mensagem de testes